"""initial_schema

Revision ID: 74909a43f209
Revises: 
Create Date: 2026-05-12 16:12:04.557368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '74909a43f209'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('contact', sa.String(length=128), nullable=False),
    sa.Column('linkedin', sa.String(length=512), nullable=False),
    sa.Column('experience', sa.Integer(), nullable=False),
    sa.Column('skills', sqlite.JSON(), nullable=False),
    sa.Column('match_score', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('current_role', sa.String(length=255), nullable=False),
    sa.Column('current_company', sa.String(length=255), nullable=False),
    sa.Column('education', sa.String(length=512), nullable=False),
    sa.Column('expected_salary', sa.String(length=128), nullable=False),
    sa.Column('notice_period', sa.String(length=128), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('resume_file', sa.String(length=512), nullable=False),
    sa.Column('applied_for', sa.String(length=255), nullable=False),
    sa.Column('applied_date', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_batches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=True),
    sa.Column('status', sa.Enum('pending_review', 'processing', 'ready_to_commit', 'committed', 'failed', 'cancelled', name='importbatchstatus', native_enum=False, length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_staging_rows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('raw_cells_json', sqlite.JSON(), nullable=False),
    sa.Column('mapped_candidate_json', sqlite.JSON(), nullable=True),
    sa.Column('issues_json', sqlite.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_staging_rows_batch_id'), 'import_staging_rows', ['batch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_import_staging_rows_batch_id'), table_name='import_staging_rows')
    op.drop_table('import_staging_rows')
    op.drop_table('import_batches')
    op.drop_table('candidates')
    # ### end Alembic commands ###
