"""slim_candidates_early_stage

Revision ID: eeb0391a8053
Revises: 30297a615535
Create Date: 2026-05-12 17:21:28.403784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eeb0391a8053'
down_revision: Union[str, Sequence[str], None] = '30297a615535'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'applied_date')
    op.drop_column('candidates', 'match_score')
    op.drop_column('candidates', 'summary')
    op.drop_column('candidates', 'status')
    op.drop_column('candidates', 'location')
    op.drop_column('candidates', 'resume_file')
    op.drop_column('candidates', 'expected_salary')
    op.drop_column('candidates', 'applied_for')
    op.drop_column('candidates', 'education')
    op.drop_column('candidates', 'notice_period')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('notice_period', sa.VARCHAR(length=128), nullable=False))
    op.add_column('candidates', sa.Column('education', sa.VARCHAR(length=512), nullable=False))
    op.add_column('candidates', sa.Column('applied_for', sa.VARCHAR(length=255), nullable=False))
    op.add_column('candidates', sa.Column('expected_salary', sa.VARCHAR(length=128), nullable=False))
    op.add_column('candidates', sa.Column('resume_file', sa.VARCHAR(length=512), nullable=False))
    op.add_column('candidates', sa.Column('location', sa.VARCHAR(length=255), nullable=False))
    op.add_column('candidates', sa.Column('status', sa.VARCHAR(length=32), nullable=False))
    op.add_column('candidates', sa.Column('summary', sa.TEXT(), nullable=False))
    op.add_column('candidates', sa.Column('match_score', sa.INTEGER(), nullable=False))
    op.add_column('candidates', sa.Column('applied_date', sa.VARCHAR(length=32), nullable=False))
    # ### end Alembic commands ###
